// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"time"
)

type BlogArticle struct {
	ID int32 `json:"id"`
	// 标签ID
	TagID int64 `json:"tag_id"`
	// 文章标题
	Title string `json:"title"`
	// 简述
	Intro   string `json:"intro"`
	Content string `json:"content"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人ID
	CreatedID int32 `json:"created_id"`
	// 修改时间
	ModifiedAt time.Time `json:"modified_at"`
	// 修改人ID
	ModifiedID int32 `json:"modified_id"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at"`
	// 状态 0为禁用、1为启用
	State int16 `json:"state"`
}

type BlogTag struct {
	ID int32 `json:"id"`
	// 标签名称
	Name string `json:"name"`
	// 创建人ID
	CreatedID int32 `json:"created_id"`
	// 修改时间
	ModifiedAt time.Time `json:"modified_at"`
	// 修改人ID
	ModifiedID int32 `json:"modified_id"`
	// 删除时间
	DeletedAt time.Time `json:"deleted_at"`
	// 状态 0为禁用、1为启用
	State int16 `json:"state"`
}

type BlogUser struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
	// 账号
	Username string `json:"username"`
	// 用户名
	Name string `json:"name"`
	// 密码
	Password string `json:"password"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 状态 0为禁用、1为启用
	State int16 `json:"state"`
}
