// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (BlogArticle, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (BlogUser, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (BlogTag, error)
	DeleteArticle(ctx context.Context, id int32) error
	DeleteAuthor(ctx context.Context, id int32) error
	DeleteTag(ctx context.Context, id int32) error
	GetArticle(ctx context.Context, id int32) (BlogArticle, error)
	GetAuthor(ctx context.Context, email string) (BlogUser, error)
	GetTag(ctx context.Context, id int32) (BlogTag, error)
	ListArticle(ctx context.Context) ([]BlogArticle, error)
	ListAuthor(ctx context.Context) ([]BlogUser, error)
	ListTag(ctx context.Context, arg ListTagParams) ([]BlogTag, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (BlogTag, error)
}

var _ Querier = (*Queries)(nil)
